### ISSUE TITLE
Strip prop types in production?

### ISSUE THREAD

**Issue by cafreeman** [ciena-blueplanet/ember-prop-types#18]
FIrst off, I *love* this addon. This brings a great pattern from the React world to Ember and I really hope more people continue to adopt it!

As a result of wanting to use it all the time, I started to wonder if the prop types make it into the production build when Ember compiles everything? I definitely want to add prop types to everything during development, but I'm hesitant to do so if it means all of that is going to get transpiled into the production bundle.

Would it be possible to strip out all the prop types when doing `ember build -prod`? Similar to this react optimization: `https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types`

I'd be happy to work on a PR for this if you think it's doable and can point me in the right direction.

**Comment by sglanzer** [comment]
This sounds like an awesome optimization!  

I assume a similar approach to `ember-hook` could be used to strip this out in production.

Use a similar function to this to detect the correct environment (!production):

https://github.com/Ticketfly/ember-hook/blob/43a0ea3a25b5f24ad591655cffec9b71e0f16f6d/addon/utils/return-when-testing.js

Then use that information in the initializer to include/exclude the mixin:

https://github.com/Ticketfly/ember-hook/blob/43a0ea3a25b5f24ad591655cffec9b71e0f16f6d/addon/helpers/hook.js

I think the other piece that would be necessary here would be splitting out the defaults into a secondary mixin, since that would still need to be provided in production.

This probably doesn't cover _all_ the corner cases, but it would be a good start

**Comment by sglanzer** [comment]
https://github.com/ciena-blueplanet/ember-prop-types/blob/master/addon/extensions/component-prop-types.js#L15 would need to be moved inside the initializer here https://github.com/ciena-blueplanet/ember-prop-types/blob/master/addon/initializers/component-prop-types.js#L14 as well

**Comment by sandersky** [comment]
I would love what you are asking for but I can say it at least doesn't run the validation in production https://github.com/ciena-blueplanet/ember-prop-types/blob/master/addon/mixins/prop-types.js#L30

**Comment by sglanzer** [comment]
Hmm, from my perspective that seems 95% sufficient

**Comment by cafreeman** [comment]
Yea, that is pretty close! I'm curious how much of a footprint the proptypes code itself has, but I can't imagine it's very significant. It may be that this isn't an optimization we need and I can just reliably start using prop types all over the place :)

**Comment by sglanzer** [comment]
Yeah, I wasn't aware that @sandersky had covered that before making my comments - I'd say the code size is negligible, so further optimization is probably time better invested elsewhere

**Comment by cafreeman** [comment]
That sounds good to me. I'll go ahead and close this issue. Thanks for the feedback!
