### ISSUE TITLE
Add `isUpdatable` (similar to `isRequired`)

### ISSUE THREAD

**Issue by job13er** [ciena-blueplanet/ember-prop-types#82]
Add a way to flag properties as being updatable. We can then wire into `didUpdateAttrs()` to make sure that only properties flagged for updates are being updated.

**Comment by sandersky** [comment]
I think I'd prefer we do the opposite and flag properties as not updatable to prevent an major change that causes major changes to every addon using `ember-prop-types`'s current API. I'm not sure if we'd go with `.notUpdatable` or something better (I can't think of anything personally).

**Comment by sandersky** [comment]
Actually come to think of it we could go with `.isImmutable`.

**Comment by job13er** [comment]
I think updateable and immutable are two different concepts. At least to me, updateable is like `let` vs. `const` can you overwrite it? Whereas immutable is can you overwrite a key in an object or add/remove elements in an array?

**Comment by sandersky** [comment]
@job13er that is a good point and after thinking about this some more this morning I think adding a property, regardless of name, will require a major version bump. This is because if I add `.notUpdatable` to the `propTypes` definitions in one addon its consumers MUST be on at least the version of `ember-prop-types` in which this feature is added. If this feature is added in a minor I'd be worried about an app consuming a previous minor of this project while one of it's addons requires the minor that includes this feature.

Adding more properties like this also causes rather large objects to be created for each definition given the current implementation. Today you end up with an object that looks like the following for each type:

```js
{
  isRequired: {
    required: true,
    type: 'string'
  },
  required: false,
  type: 'string'
}
```

Adding `notUpdatable` would end up yielding something like:

```js
{
  isRequired: {
    notUpdatable: {
      required: true,
      type: 'string',
      updatable: true
    },
    required: true,
    type: 'string',
    updatable: true
  },
  notUpdatable: {
    isRequired: {
      required: true,
      type: 'string',
      updatable: false
    },
    required: false,
    type: 'string',
    updatable: false
  },
  required: false,
  type: 'string',
  updatable: true
}
```

I think if we want to start adding more properties we need to see if we can achieve an object with dynamic getters that enables us to do something along the lines of:

```js
{
  _required: false,
  _type: 'string',
  _updatable: true,

  getter (name) {
    switch (name) {
      case 'isRequired':
        this._required = true
        break

      case 'notUpdatable':
        this._updatable = false
        break
    }

    return this
  }
}
```

I'm not sure if the above is even possible in Javascript but we may want to look into [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy).

**Comment by sandersky** [comment]
Actually I don't think the proxy would work because a single object would be shared for each use case: `isRequired`, `notUpdatable`, `isReuired` and `notUpdatable`, etc. This makes me wonder if we want to continue with the current API or introduce a new API along the lines of:

```js
import Ember from 'ember'
const {Component} = Ember

export default Component.extend(PropTypesMixin, {
  propTypes: {
    foo: PropTypes.string({
      required: true,
      updatable: false
    })
    bar: PropTypes.boolean()
    baz: PropTypes.array({
      maxLength: 2,
      minLength: 1,
      required: true
    })
  }
})
```

**Comment by job13er** [comment]
Interesting, but how would that work with something not like shape, that already accepts an object? How would you flag the shape itself as required or updateable? Particularly if the shape includes the keys `required` or `updateable`?
